version: 2
sources:
 - name: src
   database: raw
   schema: src

   tables:
     - name: orders_raw
     - name: orders_append_raw
     - name: manufacturing_production
     - name: manufacturing_orders
     - name: machine_master
     - name: machine_master_check
  
     